name: GitHub Metrics

on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora
  workflow_dispatch: # Permite execução manual

jobs:
  metrics:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
            token: ${{ secrets.METRICS_TOKEN }}
            user: markao23 # Substitua pelo seu nome de usuário
            template: classic
            config_timezone: America/Sao_Paulo # Substitua pelo seu fuso horário
            plugin_languages: yes
            plugin_languages_colors: github
            plugin_languages_limit: 10
            plugin_languages_recent: 15
            plugin_languages_sections: most-used
            plugin_languages_threshold: 0%
            plugin_habits: yes
            plugin_habits_from: 200 # Anos a serem considerado
            plugin_habits_days: 14 # Número de dias considerados para atividade recente
            plugin_habits_facts: yes # Mostrar fatos relacionados a atividades
            plugin_followup: yes
            plugin_followup_sections: repositories
            plugin_followup_indepth: yes